import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import TopNavigation from "@/app/_components/navigation/top-navigation";


export const graphik = localFont({
  src: [
    {
      path: "../public/assets/fonts/graphik/Graphik-Regular-Trial.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/graphik/Graphik-Medium-Trial.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/graphik/Graphik-Semibold-Trial.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/graphik/Graphik-Bold-Trial.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-graphik", // optional (great for Tailwind)
});

export const boring = localFont({
  src: [
    {
      path: "../public/assets/fonts/boring.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-boring", // optional (great for Tailwind)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${graphik.variable} ${boring.variable} antialiased font-graphik`}
      >
        <TopNavigation />
        {children}
      </body>
    </html>
  );
}
